services:
  db:
    image: postgres
    container_name: eyesky_db
    environment:
      POSTGRES_DB: eyesky
      POSTGRES_USER: eyesky_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
